### ISSUE TITLE
Rename this repository

### ISSUE THREAD

**Issue by ajvincent** [ajvincent/proposal-await-dictionary#1]
@ljharb correctly points out the name of this shouldn't be the solution but the problem.  Only I don't know a short description for this:  "Await dictionary of promises"?

**Comment by ljharb** [comment]
That seems reasonable - Promise.all is "a promise for a list of promises", this is more like "a promise for a map of promises".

**Comment by ajvincent** [comment]
I'll make this change tonight or tomorrow unless someone suggests otherwise:
Repository name: "proposal-await-dictionary"
Title: "Await dictionary of Promises"
