### ISSUE TITLE
How should we deal with prototypes on Promise.ownProperties()?

### ISSUE THREAD

**Issue by ajvincent** [ajvincent/proposal-await-dictionary#3]

**Comment by ljharb** [comment]
"own" typically means enumerable own properties, ie, Object.keys/entries. (`Reflect.ownKeys` is an exception, but Reflect is weird and i don't think it counts).

**Comment by ajvincent** [comment]
That's not what I meant.  I was thinking more along the lines of Object.create(), where we can specify the prototype of the object we're creating.  But such a capability doesn't exist in Object.fromEntries()...

**Comment by ljharb** [comment]
We explicitly decided not to do that in Object.fromEntries, and I assume we'd want the same decision here. Inheritance is done via `class extends`; the ES5 attempt to introduce the Object.create patterns never went anywhere.
