### ISSUE TITLE
A polyfill & testing playground?

### ISSUE THREAD

**Issue by ajvincent** [ajvincent/proposal-await-dictionary#6]
Working code defeats theory every time, and fortunately this proposal is one that we can implement in a polyfill ourselves.

I'd like very much to have an initial polyfill and a framework to run simple tests in.  Then we can flesh out the different ideas in code to see concretely what we're talking about.

@rwaldron, @ljharb, can either of you submit a pull request to add this?  Let's start with a polyfill for `Promise.ownProperties()` that just returns `{}`, and a test for the same.  Then we can write out the full polyfills on top of that.

(I'd do it myself, but I don't know what the "correct" way for TC39 is.)

**Comment by ljharb** [comment]
The correct way is not to offer a polyfill at all, imo - userland should provide them during stage 3. We can make a playground, though, without providing people code they can prematurely use in their own applications.

Either way, there’s prior art in Bluebird here - http://bluebirdjs.com/docs/api/promise.props.html - so it might be more instructive to look for existing uses of that pattern?

**Comment by ajvincent** [comment]
OK, then, how do we set up the playground?  A private repo?

**Comment by ljharb** [comment]
I'm not sure :-) very few proposals have ever done it.

It does seem a bit premature for a stage 0 proposal, though - we don't even know if the committee wants to spend time on it.

**Comment by ajvincent** [comment]
Actually, should I delete the polyfill currently on the README?

**Comment by ljharb** [comment]
Probably? At stage < 2, it's not really useful, since the shape of the solution isn't remotely solidified until then.

**Comment by ajvincent** [comment]
Done.

**Comment by ajvincent** [comment]
Closed as premature.
